# Dynamic TACACS+ configuration
#############################################################################################
# The tcp `router` requires a `rule` to be set or you will get an error
# when starting Traefik.  When setting the rule, do NOT use single quotes (')
# but instead use the backtick (`) which is located to the left of the 1 on your 
# keyboard.
# "To set the value of a rule, use backticks ` or escaped double-quotes \".
# Single quotes ' are not accepted since the values are Golang's String Literals."
# https://doc.traefik.io/traefik/routing/routers/#rule_1
#############################################################################################

tcp:
  routers:
    tacacsrouter:
      entryPoints:
      - tacacs
      rule: ClientIP(`192.168.10.0/24`, `192.168.11.0/24`, `10.1.100.0/24`)
      service: tacacs-1

  services:
    tacacs-1:
      loadBalancer:
        servers:
          - address: "ise-aws.securitydemo.net:49"
          - address: "ise-nutanix.securitydemo.net:49"